name: Demonstração para criação de PR automático

on:
  push:
    branches:
      - dev

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Create Pull Request
        id: demo
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "main"
          base: dev
          title: "Demonstração Auto PR - Hello World"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            Descrição do PR criado automaticamente - Teste
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false
          
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_DEMO }}
          number: ${{ steps.demo.outputs.pull-request-number }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.demo.outputs.pull-request-number }}
          method: squash