name: Demonstração para criação de PR automático

on:
  push:
    branches:
      - main

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Create Pull Request
        id: demo
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "dev"
          base: main
          title: "Demonstração Auto PR - Hello World"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            Descrição do PR criado automaticamente - Teste
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false
      
      - name: Get Pull Request Number
        id: get-pr-number
        run: |
    		PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository }}:${{ github.ref_name }}&state=open" | jq '.[0].number')
    		echo "pull_request_number=$PR_NUMBER" >> $GITHUB_ENV
    
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_DEMO }}
          number: ${{ env.pull_request_number }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ env.pull_request_number }}
          method: squash